### ISSUE TITLE
使用混淆替换命令提示undefined local variable or method

### ISSUE THREAD

**Issue by Musk66** [kaich/codeobscure#46]
使用的命令是codeobscure -o temp02/temp01.xcodeproj -f f,w，
工程中代码很简单，两个ViewController类
/Library/Ruby/Gems/2.6.0/gems/codeobscure-0.1.8.0/lib/codeobscure.rb:138:in `obscure': undefined local variable or method `path' for Codeobscure:Module

是不是哪个参数或者配置不对，谢谢

**Comment by Musk66** [comment]
> 使用的命令是codeobscure -o temp02/temp01.xcodeproj -f f,w，
> 工程中代码很简单，两个ViewController类
> /Library/Ruby/Gems/2.6.0/gems/codeobscure-0.1.8.0/lib/codeobscure.rb:138:in `obscure': undefined local variable or method `path' for Codeobscure:Module
> 
> 是不是哪个参数或者配置不对，谢谢
